// generator.rs — Idempotent bash install script emitter
// Developed for Lean Linux by archerprojects (archer.projects@proton.me)
// https://github.com/archerprojects/app-inventory-generator
//
// Generates a package-install-only script. Config migration is out of scope.
// Per-package commented blocks, one command per line, 80-char width.
// Safe to re-run — every install is guarded by a presence check.

use std::fs;
use std::path::PathBuf;

use crate::resolver::{Resolution, TargetDistro};

/// A resolved package ready for script emission.
#[derive(Debug, Clone)]
pub struct ResolvedPackage {
    /// Human-readable name shown in script comments.
    pub display_name: String,
    pub resolution: Resolution,
}

/// All inputs required to generate the script.
pub struct GeneratorInput<'a> {
    pub packages: &'a [ResolvedPackage],
    pub target: &'a TargetDistro,
}

/// Generate and write the bash script to ~/app_inventory/<slug>_app_install.sh.
/// Creates ~/app_inventory/ if it doesn't exist. Overwrites existing file
/// for the same target — one script per target, regeneration replaces it.
/// Returns the output path on success.
pub fn generate(input: &GeneratorInput) -> Result<PathBuf, String> {
    let script = build_script(input);
    let home = std::env::var("HOME").map_err(|_| "HOME not set".to_string())?;

    let out_dir = PathBuf::from(home).join("app_inventory");
    fs::create_dir_all(&out_dir)
        .map_err(|e| format!("Failed to create ~/app_inventory: {e}"))?;

    let filename = format!("{}_app_install.sh", input.target.slug());
    let out_path = out_dir.join(filename);

    fs::write(&out_path, &script)
        .map_err(|e| format!("Failed to write script: {e}"))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&out_path)
            .map_err(|e| e.to_string())?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&out_path, perms).map_err(|e| e.to_string())?;
    }

    Ok(out_path)
}

fn build_script(input: &GeneratorInput) -> String {
    let mut s = String::new();

    // ── File header ───────────────────────────────────────────────────────
    s.push_str("#!/usr/bin/env bash\n");
    s.push_str("# ============================================================\n");
    s.push_str(&format!("# {}_app_install.sh\n", input.target.slug()));
    s.push_str("# Generated by App Inventory Generator\n");
    s.push_str("# Developed for Lean Linux by archerprojects\n");
    s.push_str("# archer.projects@proton.me\n");
    s.push_str("# ------------------------------------------------------------\n");
    s.push_str(&format!("# Target distro : {}\n", input.target.label()));
    s.push_str(&format!("# Generated     : {}\n", chrono_now()));
    s.push_str("# ------------------------------------------------------------\n");
    s.push_str("#\n");
    s.push_str("# WHAT THIS SCRIPT DOES\n");
    s.push_str("# Installs the packages you selected on your new system.\n");
    s.push_str("# Each package is checked before install — safe to re-run.\n");
    s.push_str("#\n");
    s.push_str("# WHAT THIS SCRIPT DOES NOT DO\n");
    s.push_str("# This script does not migrate application settings or config.\n");
    s.push_str("# See the CONFIG MIGRATION NOTES section at the bottom of\n");
    s.push_str("# this file for guidance on moving your settings manually.\n");
    s.push_str("#\n");
    s.push_str("# HOW TO USE\n");
    s.push_str("# 1. Copy this file to your new system (USB drive, email, etc)\n");
    s.push_str("# 2. Open a terminal on the new system\n");
    s.push_str(&format!("# 3. Run: bash {}_app_install.sh\n", input.target.slug()));
    s.push_str("# ============================================================\n\n");

    s.push_str("set -euo pipefail\n\n");
    s.push_str("command_exists() { command -v \"$1\" &>/dev/null; }\n\n");

    // Partition snaps up-front — install where snapd is available, list otherwise.
    let snaps: Vec<&ResolvedPackage> = input
        .packages
        .iter()
        .filter(|p| matches!(p.resolution, Resolution::Snap { .. }))
        .collect();
    let snaps_installable = snap_installable(input.target);

    // ── Flatpak bootstrap ─────────────────────────────────────────────────
    let has_flatpak = input
        .packages
        .iter()
        .any(|p| matches!(p.resolution, Resolution::Flatpak(_)));

    if has_flatpak {
        s.push_str("# ------------------------------------------------------------\n");
        s.push_str("# Flatpak — install runtime and add Flathub remote\n");
        s.push_str("# ------------------------------------------------------------\n\n");
        s.push_str(flatpak_bootstrap(input.target));
        s.push('\n');
    }

    // ── Snap bootstrap ────────────────────────────────────────────────────
    if snaps_installable && !snaps.is_empty() {
        s.push_str("# ------------------------------------------------------------\n");
        s.push_str("# Snap — install snapd\n");
        s.push_str("# ------------------------------------------------------------\n\n");
        s.push_str(snap_bootstrap(input.target));
        s.push('\n');
    }

    // ── Native packages ───────────────────────────────────────────────────
    let native: Vec<&ResolvedPackage> = input
        .packages
        .iter()
        .filter(|p| matches!(p.resolution, Resolution::Native(_)))
        .collect();

    if !native.is_empty() {
        s.push_str("# ------------------------------------------------------------\n");
        s.push_str("# Native packages\n");
        s.push_str("# ------------------------------------------------------------\n\n");
        for pkg in &native {
            if let Resolution::Native(ref name) = pkg.resolution {
                s.push_str(&package_block_native(
                    &pkg.display_name,
                    name,
                    input.target,
                ));
            }
        }
    }

    // ── Flatpak packages ──────────────────────────────────────────────────
    let flatpaks: Vec<&ResolvedPackage> = input
        .packages
        .iter()
        .filter(|p| matches!(p.resolution, Resolution::Flatpak(_)))
        .collect();

    if !flatpaks.is_empty() {
        s.push_str("# ------------------------------------------------------------\n");
        s.push_str("# Flatpak packages\n");
        s.push_str("# ------------------------------------------------------------\n\n");
        for pkg in &flatpaks {
            if let Resolution::Flatpak(ref id) = pkg.resolution {
                s.push_str(&package_block_flatpak(&pkg.display_name, id));
            }
        }
    }

    // ── Snap packages ─────────────────────────────────────────────────────
    if snaps_installable && !snaps.is_empty() {
        s.push_str("# ------------------------------------------------------------\n");
        s.push_str("# Snap packages\n");
        s.push_str("# ------------------------------------------------------------\n\n");
        for pkg in &snaps {
            if let Resolution::Snap { ref name, classic } = pkg.resolution {
                s.push_str(&package_block_snap(&pkg.display_name, name, classic));
            }
        }
    }

    // ── Manual install — not auto-installed on this target ─────────────────
    // Covers packages with no target equivalent, plus snaps on distros that
    // do not ship snapd. Listed with a note so the user can install them.
    let unresolved: Vec<&ResolvedPackage> = input
        .packages
        .iter()
        .filter(|p| matches!(p.resolution, Resolution::Unresolved))
        .collect();
    let snaps_manual: &[&ResolvedPackage] =
        if snaps_installable { &[] } else { snaps.as_slice() };

    if !unresolved.is_empty() || !snaps_manual.is_empty() {
        s.push_str("# ------------------------------------------------------------\n");
        s.push_str("# Manual install — not auto-installed on this target\n");
        s.push_str("# Install these yourself after running this script.\n");
        s.push_str("# ------------------------------------------------------------\n");
        s.push('\n');
        for pkg in &unresolved {
            s.push_str(&format!(
                "# {} — no package found for the target distro.\n",
                pkg.display_name
            ));
            s.push_str("#   Locate and install it with your package manager.\n");
        }
        for pkg in snaps_manual {
            if let Resolution::Snap { ref name, classic } = pkg.resolution {
                let flag = if classic { " --classic" } else { "" };
                s.push_str(&format!("# {} (snap)\n", pkg.display_name));
                s.push_str(&format!(
                    "#   snapd is not in the default repositories for {}.\n",
                    input.target.label()
                ));
                s.push_str(&format!(
                    "#   Install snapd, then run: sudo snap install {}{}\n",
                    name, flag
                ));
            }
        }
        s.push('\n');
    }

    // ── Done ──────────────────────────────────────────────────────────────
    s.push_str("# ------------------------------------------------------------\n");
    s.push_str("echo \"\"\n");
    s.push_str("echo \"Install complete.\"\n");
    s.push_str("echo \"\"\n\n");

    // ── Config migration notes ────────────────────────────────────────────
    s.push_str("# ============================================================\n");
    s.push_str("# WHAT THIS APP AND SCRIPT DOES\n");
    s.push_str("# ============================================================\n");
    s.push_str("#\n");
    s.push_str("# The app scans your system for installed apps (native or\n");
    s.push_str("# Flatpak) and allows you to select which apps to install on\n");
    s.push_str("# a new system. This script, when run in terminal, will\n");
    s.push_str("# auto-install your selected packages on the new system.\n");
    s.push_str("# This app can be run on any Linux system to install the\n");
    s.push_str("# required apps providing that system was set as target in\n");
    s.push_str("# the original script to confirm the proper install codes\n");
    s.push_str("# and sequence for the new system requirements were met.\n");
    s.push_str("#\n");
    s.push_str("# ============================================================\n");
    s.push_str("# WHAT THIS APP DOES NOT DO\n");
    s.push_str("# ============================================================\n");
    s.push_str("#\n");
    s.push_str("# It does not migrate application settings or configuration\n");
    s.push_str("# files. On an existing system that you are reinstalling,\n");
    s.push_str("# these files are usually already in place and reinstalling\n");
    s.push_str("# the app will configure to these existing settings. On a\n");
    s.push_str("# fresh install, these files must be moved manually.\n");
    s.push_str("#\n");
    s.push_str("# ============================================================\n");
    s.push_str("# MOVING YOUR SETTINGS\n");
    s.push_str("# ============================================================\n");
    s.push_str("#\n");
    s.push_str("# Separate home partition:\n");
    s.push_str("#   Mount it on the new system. Most settings come back\n");
    s.push_str("#   automatically.\n");
    s.push_str("#\n");
    s.push_str("# Copying your home directory:\n");
    s.push_str("#   On the old system run:\n");
    s.push_str("#     tar -czf ~/home-backup.tar.gz \\\n");
    s.push_str("#       ~/.config ~/.bashrc ~/.gitconfig\n");
    s.push_str("#   Copy to USB, then on new system:\n");
    s.push_str("#     tar -xzf home-backup.tar.gz -C ~/\n");
    s.push_str("#\n");
    s.push_str("# Browsers:\n");
    s.push_str("#   Firefox  — sign in to Firefox Sync\n");
    s.push_str("#   Chrome   — sign in to your Google account\n");
    s.push_str("#   Brave    — use brave://settings/braveSync\n");
    s.push_str("#\n");
    s.push_str("# Thunderbird:\n");
    s.push_str("#   Use Import/Export Tools addon or copy ~/.thunderbird\n");
    s.push_str("#\n");
    s.push_str("# VSCode:\n");
    s.push_str("#   Sign in with Settings Sync.\n");
    s.push_str("#\n");
    s.push_str("# Some settings can also be moved through profile\n");
    s.push_str("# configurations on different browsers and mail clients.\n");
    s.push_str("# Check internet sources for more detailed information\n");
    s.push_str("# concerning your particular app regarding moving passwords,\n");
    s.push_str("# bookmarks and mail settings during migration if needed.\n");
    s.push_str("#\n");
    s.push_str("# ============================================================\n");

    s
}

/// Per-package block for a native package.
/// Format: comment with app name, idempotent check, install command.
fn package_block_native(
    display: &str,
    pkg_name: &str,
    target: &TargetDistro,
) -> String {
    use crate::resolver::TargetDistro::*;

    let (check, install) = match target {
        Debian | Ubuntu | Mint | PopOs => (
            format!("dpkg -s {} &>/dev/null", pkg_name),
            format!("sudo apt-get install -y {}", pkg_name),
        ),
        Fedora => (
            format!("rpm -q {} &>/dev/null", pkg_name),
            format!("sudo dnf install -y {}", pkg_name),
        ),
        Arch | Manjaro => (
            format!("pacman -Q {} &>/dev/null", pkg_name),
            format!("sudo pacman -S --noconfirm {}", pkg_name),
        ),
        OpenSuse => (
            format!("rpm -q {} &>/dev/null", pkg_name),
            format!("sudo zypper install -y {}", pkg_name),
        ),
    };

    format!(
        "# {display}\n\
         if ! {check}; then\n\
         \t{install}\n\
         fi\n\n"
    )
}

/// Per-package block for a Flatpak app.
fn package_block_flatpak(display: &str, id: &str) -> String {
    format!(
        "# {display}\n\
         if ! flatpak info {id} &>/dev/null; then\n\
         \tflatpak install -y flathub {id}\n\
         fi\n\n"
    )
}

/// Flatpak bootstrap block.
fn flatpak_bootstrap(target: &TargetDistro) -> &'static str {
    use crate::resolver::TargetDistro::*;
    match target {
        Debian | Ubuntu | Mint | PopOs =>
            "if ! command_exists flatpak; then\n\
             \tsudo apt-get install -y flatpak\n\
             fi\n\
             if ! flatpak remote-list | grep -q flathub; then\n\
             \tflatpak remote-add --if-not-exists flathub \\\n\
             \t\thttps://dl.flathub.org/repo/flathub.flatpakrepo\n\
             fi\n",
        Fedora =>
            "if ! command_exists flatpak; then\n\
             \tsudo dnf install -y flatpak\n\
             fi\n\
             if ! flatpak remote-list | grep -q flathub; then\n\
             \tflatpak remote-add --if-not-exists flathub \\\n\
             \t\thttps://dl.flathub.org/repo/flathub.flatpakrepo\n\
             fi\n",
        Arch | Manjaro =>
            "if ! command_exists flatpak; then\n\
             \tsudo pacman -S --noconfirm flatpak\n\
             fi\n\
             if ! flatpak remote-list | grep -q flathub; then\n\
             \tflatpak remote-add --if-not-exists flathub \\\n\
             \t\thttps://dl.flathub.org/repo/flathub.flatpakrepo\n\
             fi\n",
        OpenSuse =>
            "if ! command_exists flatpak; then\n\
             \tsudo zypper install -y flatpak\n\
             fi\n\
             if ! flatpak remote-list | grep -q flathub; then\n\
             \tflatpak remote-add --if-not-exists flathub \\\n\
             \t\thttps://dl.flathub.org/repo/flathub.flatpakrepo\n\
             fi\n",
    }
}

/// True if the target distro ships snapd in its default repositories.
/// Snaps are installed on these targets and listed for manual install on
/// the rest (Arch/Manjaro need the AUR; openSUSE needs a community repo).
fn snap_installable(target: &TargetDistro) -> bool {
    use crate::resolver::TargetDistro::*;
    matches!(target, Debian | Ubuntu | Mint | PopOs | Fedora)
}

/// Per-package block for a Snap app. Emits --classic where the snap is
/// classic-confined (captured at scan time).
fn package_block_snap(display: &str, name: &str, classic: bool) -> String {
    let flag = if classic { " --classic" } else { "" };
    format!(
        "# {display}\n\
         if ! snap list {name} &>/dev/null; then\n\
         \tsudo snap install {name}{flag}\n\
         fi\n\n"
    )
}

/// Snap bootstrap block — install snapd. Only emitted for targets that ship
/// snapd. Fedora also needs the /snap symlink for classic snap support.
fn snap_bootstrap(target: &TargetDistro) -> &'static str {
    use crate::resolver::TargetDistro::*;
    match target {
        Debian | Ubuntu | Mint | PopOs =>
            "if ! command_exists snap; then\n\
             \tsudo apt-get install -y snapd\n\
             fi\n",
        Fedora =>
            "if ! command_exists snap; then\n\
             \tsudo dnf install -y snapd\n\
             \tsudo ln -sf /var/lib/snapd/snap /snap\n\
             fi\n",
        // Arch/Manjaro/openSUSE never reach here — their snaps are listed
        // in the manual-install section instead.
        Arch | Manjaro | OpenSuse => "",
    }
}

fn chrono_now() -> String {
    std::process::Command::new("date")
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".to_string())
}
